[colors.primary]
background = "#1E222A"
foreground = "#D8DEE9"

[colors.cursor]
text = "#242933"
cursor = "#D8DEE9"

[colors.selection]
text = "#ECEFF4"
background = "#3B4252"

[colors.normal]
black   = "#2E3440"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#88C0D0"
white   = "#E5E9F0"

[colors.bright]
black   = "#434C5E"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#81A1C1"
magenta = "#B48EAD"
cyan    = "#8FBCBB"
white   = "#ECEFF4"
