;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #1d1f21
background-alt = #282a2e
foreground = #c5c8c6
alert = #cc241d
primary = #81a2be
secondary = #6C1967
darkred = #44266C
red = #B72430
darkgreen = #95165F
green = #472E88
darkyellow = #4736A8
yellow = #a3a2d3 
darkblue = #727193 
blue = #6C1967
darkpurple = #44266C
purple = #B72430
darkaqua = #95165F
aqua = #472E88
gray = #4736A8
darkbg = #1d2021
lightbg = #32302f
lightbg2 = #3c3836
darkorange = #d65d0e
orange = #fe8019
disabled = #727193

[bar/bar]
width = 90%
height = 24pt
bottom = false
offset-x = 5%
;override-redirect = true
radius = 4

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 3pt
border-color = #00000000
; border-left-size = 10
; border-right-size = 10

padding-left = 1
padding-right = 1

module-margin = 0 

separator = 
separator-foreground = ${colors.disabled}

font-0 = "MesloLGS Nerd Font Mono:size=11;2"
font-1 = "MesloLGS Nerd Font Mono:size=20;4"
font-2 = "Material Design Icons:style=Bold:size=20;4"

modules-left = space launcher space space xworkspaces space xwindow
modules-right = space xkeyboard space memory space date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
pin-workspaces = false
; tray-position = right

; wm-restack = generic
wm-restack = bspwm
; wm-restack = i3

# override-redirect = true

[module/space]
type=custom/text
content = " "
content-foreground = #00ffffff
content-font = 4
content-padding = 0

[glyph]
gleft = 
gright = 

[module/right1]
type = custom/text
content-background = ${colors.Background}
content-foreground = ${colors.Cyan}
content = ${glyph.gright}
content-font = 2

[module/right2]
type = custom/text
content-background = ${colors.Cyan}
content-foreground = ${colors.Green}
content = ${glyph.gright}
content-font = 2

[module/right3]
type = custom/text
content-background = ${colors.Green}
content-foreground = ${colors.Orange}
content = ${glyph.gright}
content-font = 2

[module/right4]
type = custom/text
content-background = ${colors.Orange}
content-foreground = ${colors.Pink}
content = ${glyph.gright}
content-font = 2

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/pipewire]
type = internal/pipewire

sink = @DEFAULT_SINK@

format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = ${colors.Red}
format-volume = <label-volume>
format-volume-foreground = ${colors.Red}

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.Red}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
label-layout = "%{T2}󰇧%{T-} %layout%"
label-layout-foreground = ${colors.Green}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.Green}
label-padding = 1

[module/memory]
type = internal/memory
interval = 2
format-prefix = "%{T2}󰍛%{T-} "
format-prefix-foreground = ${colors.Yellow}
label = %percentage_used:2%%
label-foreground = ${colors.Yellow}

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = "%{T2}%{T-} %date%"
label-foreground = ${colors.Blue}

label-padding = 1

[module/launcher]
type = custom/text

content = "%{T2}%{T-}"
content-foreground = ${colors.foreground}

click-left = rofi -show drun
click-right = launcher_t1

[settings]
screenchange-reload = true
pseudo-transparency = true

